# Generated by Django 4.2.5 on 2023-09-25 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
    ]
